openapi: 3.0.3
info:
  title: Django DRF Task Manager
  version: 0.0.0
paths:
  /api/LoginAPI/:
    post:
      operationId: LoginAPI_create
      description: Authenticate user and return auth token.
      tags:
      - LoginAPI
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - tokenAuth: []
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
          description: ''
  /api/RegisterAPI/:
    post:
      operationId: RegisterAPI_create
      description: Handle user registration.
      tags:
      - RegisterAPI
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - tokenAuth: []
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - tokenAuth: []
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/taskInformation/:
    get:
      operationId: taskInformation_list
      description: CRUD API for TaskInfo model with authentication and pagination.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - taskInformation
      security:
      - tokenAuth: []
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTaskInfoList'
          description: ''
    post:
      operationId: taskInformation_create
      description: CRUD API for TaskInfo model with authentication and pagination.
      tags:
      - taskInformation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInfo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TaskInfo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TaskInfo'
        required: true
      security:
      - tokenAuth: []
      - basicAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskInfo'
          description: ''
  /api/taskInformation/{id}/:
    get:
      operationId: taskInformation_retrieve
      description: CRUD API for TaskInfo model with authentication and pagination.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this task info.
        required: true
      tags:
      - taskInformation
      security:
      - tokenAuth: []
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskInfo'
          description: ''
    put:
      operationId: taskInformation_update
      description: CRUD API for TaskInfo model with authentication and pagination.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this task info.
        required: true
      tags:
      - taskInformation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInfo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TaskInfo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TaskInfo'
        required: true
      security:
      - tokenAuth: []
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskInfo'
          description: ''
    patch:
      operationId: taskInformation_partial_update
      description: CRUD API for TaskInfo model with authentication and pagination.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this task info.
        required: true
      tags:
      - taskInformation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTaskInfo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTaskInfo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTaskInfo'
      security:
      - tokenAuth: []
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskInfo'
          description: ''
    delete:
      operationId: taskInformation_destroy
      description: CRUD API for TaskInfo model with authentication and pagination.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this task info.
        required: true
      tags:
      - taskInformation
      security:
      - tokenAuth: []
      - basicAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Login:
      type: object
      description: Serializer for handling user login authentication.
      properties:
        username:
          type: string
        password:
          type: string
          writeOnly: true
      required:
      - password
      - username
    PaginatedTaskInfoList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/TaskInfo'
    PatchedTaskInfo:
      type: object
      description: Serializer for TaskInfo model, including read-only user data.
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 100
        description:
          type: string
        due_date:
          type: string
          format: date
          nullable: true
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
    Register:
      type: object
      description: Serializer for user registration with validation for duplicates.
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
      - username
    TaskInfo:
      type: object
      description: Serializer for TaskInfo model, including read-only user data.
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 100
        description:
          type: string
        due_date:
          type: string
          format: date
          nullable: true
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
      required:
      - id
      - title
      - user
    User:
      type: object
      description: Serializer for Django's built-in User model (limited to username).
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
      required:
      - username
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
